### ISSUE TITLE
Bootlogo doesn't appear

### ISSUE THREAD

**Issue by rprasanth** [varigit/linux-imx#16] opened 2022-10-14 06:06 UTC
Hi All,

Could you guys see the botologo appears while booting the variscite devices?

I'm using var_dvk_mx6,

**Comment by varigigi** [comment] 2022-10-14 12:59
Hi @rprasanth,
we have no reports of similar behaviors, at least using our default kernel configuration and our EVKs.
If you need help for BSP customization (custom carrier and/or display) you may want to contact Variscite sales representative.
Please let me know if you need further details or I can close this issue.
Thanks
Best Regards
Pier

**Comment by rprasanth** [comment] 2022-10-17 12:19
Hi Pier,

I'm using Quad board which is an EVK, I don't see the bootlogo in my HDMI, Could you see that?
tried both Yocto build and recovery image from the var-wiki.

uImage & imx6q-var-som-cap.dtb were used.

```
Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.142+gdbe97925c58b (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP PREEMPT Mon Nov 1 22:51:37 UTC 2021
[    0.000000] CPU: ARMv7 Processor [412fc09a] revision 10 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Variscite i.MX6 Quad/Dual VAR-SOM-MX6
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x3c000000, size 320 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] percpu: Embedded 15 pages/cpu s32332 r8192 d20916 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 259840
[    0.000000] Kernel command line: console=ttymxc0,115200 ip=dhcp root=/dev/mmcblk0p2 rw rootwait video=mxcfb0:dev=hdmi,1280x800M@60,if=RGB24
```

**Comment by rprasanth** [comment] 2022-10-17 13:56
whereas in my 4.1 sdk, it was working. But in the recent 5.4, i couldn't see the boot logo

**Comment by varigigi** [comment] 2022-10-17 16:22
Hi @rprasanth,
you may want to check the differences in the kernel configuration.
If any dependency has been changed to be a " module", the HDMI display will not be active until the relevant modules are loaded.

**Comment by rprasanth** [comment] 2022-10-17 21:21
Hi,

I have verified the configuration but it doesn't seem helpful. Could you see the same issue?
Do you have any idea about getting a quick fix for this?

**Comment by varigigi** [comment] 2022-10-17 21:45
Hi @rprasanth,
I can't reproduce this behavior using the LVDS display.
I can reproduce it only with HDMI, using both NXP EVK and Variscite EVK.
I'm expecting some timing or driver flow changed in the kernel 5.4, preventing the logo from being shown, even if HDMI driver is loaded in the very early stage of the boot
````
[    0.000000] Kernel command line: console=ttymxc0,115200 root=/dev/mmcblk2p1 rootwait rw video=mxcfb0:dev=hdmi,1920x1080M@60,if=RGB24 video=mxcfb1:off video=mxcfb2:off video=mxcfb3:off
[    0.231345] mxc_hdmi 20e0000.hdmi_video: 20e0000.hdmi_video supply HDMI not found, using dummy regulator
[    0.233634] mxc_hdmi 20e0000.hdmi_video: Detected HDMI controller 0x13:0xa:0xa0:0xc1
[    0.233769] mxc_sdc_fb fb@0: registered mxc display driver hdmi
````
A dedicated investigation is required to identify the difference against previous kernel, but I cannot find any quick fix in the NXP documentation.
Please let me know if you need further details.
Thanks
Best Regards
Pier

**Comment by rprasanth** [comment] 2022-10-17 21:57
Hi,

Thanks for confirming the issue with HDMI,
Let us keep this issue open, which can help us to get any fix. I am also working on it.

**Comment by rprasanth** [comment] 2022-10-25 11:16
Hi,

I verified the commits which fixes the issue.

**Closed as completed** 2024-11-12 19:19 UTC
