### ISSUE TITLE
Building "lf-5.10.y_var04" for DART-6UL fails

### ISSUE THREAD

**Issue by davidatrsp** [varigit/linux-imx#18] opened 2023-01-06 13:01 UTC
Hej
Building the "lf-5.10.y_var04" branch at current head (https://github.com/varigit/linux-imx/commit/32517d87926efb61d38cb05ddad932ebfa0526f7) for the DART-6UL SOM fails for two reasons. The "lf-5.10.y_var04" branch is the suggested version for DART-6UL by the wiki (https://variwiki.com/index.php?title=Yocto_Build_Linux&release=mx6ul-yocto-hardknott-5.10.72_2.2.1-v1.0).
Looks like both of the reason were present  and solved on branch "5.4-2.1.x-imx_var01".
Note: using custom gcc 11.x toolchain and custom defconfig derived from the provided "imx_v7_var_defconfig".

Reasons for failure:
- irq-imx-irqsteer
   Solved by https://github.com/varigit/linux-imx/commit/391a7c6dfd13dbece8211b269d74c37875da0f67
- busfreq-imx
   Solved by the following commits:
   - https://github.com/varigit/linux-imx/commit/4f49200132e6d252cca49d5d97be69a7a26495a2
   - https://github.com/varigit/linux-imx/commit/e85ce3157725a6e3e77a17d6c4e0acec9de1d690

Applying these 3 commits enables the build to finish and yields a bootable kernel.

**Comment by varigigi** [comment] 2023-01-08 23:09
Hi @davidatrsp,
I've repeated the steps in the wiki, but using the official imx_v7_var_defconfig I'm not able to reproduce the failure you described.
Is a custom defconfig mandatory required ?
Thanks
Best Regards

**Comment by davidatrsp** [comment] 2023-01-09 08:51
Hej @varigigi
Did the same with our custom toolchain and I can confirm that "imx_v7_var_defconfig" builds fine. So did some further digging.

- irq-imx-irqsteer
   This issue is triggered by explicitly disabling "SUSPEND" in our custom defconfig. This is a requirement, thus patching looks to be the only solution.

- busfreq-imx
   This issue triggered by enabling only "SOC_IMX6UL" in our custom defconfig. The "imx_v7_var_defconfig" also enables "SOC_IMX6SX" that compiles both "ddr3_freq_imx6sx" and "lpddr2_freq_imx6sx" thus solving the issue.
   Enabling "SOC_IMX6SX" in out defconfig is a possible solution but it sets extra symbols and those need a review. Since the patches are one-liners, patching looks simpler than enabling "SOC_IMX6SX".

**Comment by varigigi** [comment] 2024-11-12 19:27
Hi @davidatrsp,
being the problem not reproducible with the official BSP, for the time being I'm closing this issue.
If you need further assistance, please open a dedicated ticket using your account in [Variscite Customer Portal](https://varisciteportal.axosoft.com/).
Thanks
Best Regards

**Closed as completed by varigigi** 2024-11-12 19:27 UTC
